# Generated by Django 3.2 on 2024-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('grupo', models.CharField(max_length=100)),
                ('cancion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]
